name: Master Branch

on:
  push:
    branches:
      - 'master'

jobs:
  artifact:
    name: Publish - GitHub Packages
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging

  docker:
    name: push docker-image to dockerhub
    runs-on: ubuntu-18.04
    needs: [artifact]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v2
      - name: Downloading created package
      - uses: actions/download-artifact@v1
        with:
          name: Package
      - run: cp staging/*.jar target/
      - run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - run: docker push $REPO
